package com.alexander.spring.r_chan.r_chan.enums;

public enum Actions {
    POST_CREATED,
    POST_UPDATED,
    POST_DELETED,
    POST_APPROVED,
    POST_REJECTED,
    POST_FILE_DELETED,
    POST_FILE_HIDDEN,
    POST_FILE_RESTORED,

    REPOST_CREATED,
    REPOST_UPDATED,
    REPOST_DELETED,
    REPOST_APPROVED,
    REPOST_REJECTED,

    SECTION_CREATED,
    SECTION_UPDATED,
    SECTION_DELETED,

    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_ROLE_CHANGED,
    USER_EMAIL_VERIFIED,
    USER_PASSWORD_CHANGED,
}
